### ISSUE TITLE
Theories first

### ISSUE THREAD

**Issue by JacquesCarette** [JacquesCarette/TheoriesAndDataStructures#7]
I *believe* (but am quite willing to discuss this) that we should take theories as primary, and structure the paper around theories and their names.

What we should not do then, is structure things around our **interpretation** of the data-structure underlying the 'free theories' (and their names). Yes, we do need to provide that interpretation, it is a useful result. But the exposition of the ideas need to have an order. And I believe that 
- Theory --> Free Theory --> Interpretation of underlying data-structure

is the right order in which to expose the ideas.

**Comment by alhassy** [comment]
Please see commit 4fb450b1e4ce5169af7843c92d0bb1dda5fdc44c.

Is this what you had in mind?

**Comment by JacquesCarette** [comment]
A tiny bit closer, but still very far.  Such paragraphs as

> Since our readership is intended to be a computing audience, there is little
 to be gained by starting out with data-structures then observing they have a particular
 algebraic structure. Instead, we propose to begin with tremendously simple interfaces
 which may arise in computing situations, then briefly form outline their theory.
 From there, we may then obtain a free theory and discuss its interpretation
 as a familiar data-structure.

are entirely unhelpful. It is condescending and arrogant.  The tone continues in the next paragraphs.

After some code, you say
>  Now that we have demonstrated the utility of the interface, let us analyse its theory.

which is simply not true, you have 'demonstrated' no such thing.

What is wrong with what I wrote - why can't you use that as a starting point? Also, why not indeed start from Monoid?

Again, I am willing to accept a different way to tell the story. But I'd rather you **propose** an alternate story and explain why it is pedagogically better, rather than spend a lot of time writing meandering prose that doesn't seem to have a clear aim.

**Comment by JacquesCarette** [comment]
This issue too is moot.
